name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip zlib1g-dev libltdl-dev libffi-dev libssl-dev autoconf autotools-dev python3-pip
          # Cython'u kullanıcı dizinine değil, sistem dizinine kuruyoruz:
          sudo pip3 install "cython<3.0.0" buildozer 

      - name: Build with Buildozer
        run: |
          # Buildozer'ı sudo olmadan çalıştırıyoruz ama yolu tanıtıyoruz
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
