name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3 python3-dev zip unzip zlib1g-dev libltdl-dev libffi-dev libssl-dev autoconf autotools-dev
          pip3 install --user --upgrade buildozer cython
      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
